<?php

return array(
    //admin panel
    'admin/login' => 'admin/login', 
    'admin/logout' => 'admin/logout',   
    'admin/statistics/([0-9]+)/([0-9]+)' => 'admin/statistics/$1/$2',
    'admin/trainer_info/([0-9]+)' => 'admin/trainer_info/$1',   
    'admin/trainers' => 'admin/trainers',   
    'admin/student_info/([0-9]+)' => 'admin/student_info/$1',   
    'admin/students' => 'admin/students',   
    'admin/student/([0-9]+)' => 'admin/student/$1', 
    'admin/trainer/([0-9]+)' => 'admin/trainer/$1', 
    'admin/student' => 'admin/student/0',   
    'admin/trainer' => 'admin/trainer/0',   
    'admin' => 'admin/page',

    //explore and programs pages
    'explore/add_comment/([0-9]+)' => 'explore/add_comment/$1', 
    'explore/del_comment/([0-9]+)' => 'explore/del_comment/$1', 
    'explore/load/([0-9]+)/([0-9]+)' => 'explore/load/$1/$2',   
    'explore/cart' => 'explore/cart',
    'explore/add/([0-9]+)' => 'explore/add/$1',
    'explore/new' => 'explore/new', 
    'explore/del/([0-9]+)' => 'explore/del/$1', 
    'explore/edit/([0-9]+)' => 'explore/edit/$1',   
    'explore/recomend/([0-9]+)/([0-9]+)' => 'explore/recomend/$1/$2',   
    'explore/program/([0-9]+)' => 'explore/program/$1', 
    'explore' => 'explore/page',    

    //work with targets
    'targets/del/([0-9]+)/([0-9]+)/([0-9]+)/([0-9]+)' => 'targets/del/$1/$2/$3/$4', 
    'targets/done/([0-9]+)/([0-9]+)/([0-9]+)/([0-9]+)' => 'targets/done/$1/$2/$3/$4',   
    'targets/edit/([0-9]+)/([0-9]+)/([0-9]+)/([0-9]+)' => 'targets/edit/$1/$2/$3/$4',   
    'targets/new/([0-9]+)/([0-9]+)/([0-9]+)' => 'targets/new/$1/$2/$3', 

    //lessons
    'lesson/add_comment/([0-9]+)' => 'lesson/add_comment/$1', 
    'lesson/del_comment/([0-9]+)' => 'lesson/del_comment/$1', 
    'lesson/comments/([0-9]+)/([0-9]+)' => 'lesson/comments/$1/$2', 
    'lesson/del/([0-9]+)' => 'lesson/del/$1',   
    'lesson/edit_p/([0-9]+)' => 'lesson/edit_p/$1', 
    'lesson/edit/([0-9]+)' => 'lesson/edit/$1', 
    'lesson/new_p/([0-9]+)' => 'lesson/new_p/$1',   
    'lesson/new/([0-9]+)/([0-9]+)' => 'lesson/new/$1/$2',   
    'lesson/done/([0-9]+)' => 'lesson/done/$1', 
    'lesson/([0-9]+)' => 'lesson/page/$1',  

    //trainer page
    'trainer/edit' => 'trainer/edit',	
    'trainer/delnote/([0-9]+)' => 'trainer/delnote/$1', 
    'trainer/newnote' => 'trainer/newnote', 
    'trainer/callback/([0-9]+)/([0-9]+)' => 'trainer/callback/$1/$2',   
    'trainer/delpriv/([0-9]+)' => 'trainer/delpriv/$1', 
    'trainer/newpriv' => 'trainer/newpriv', 
    'trainer/delreview/([0-9]+)' => 'trainer/delreview/$1', 
    'trainer/newreview/([0-9]+)' => 'trainer/newreview/$1', 
    'trainer/delblog/([0-9]+)' => 'trainer/delblog/$1', 
    'trainer/newblog' => 'trainer/newblog', 
    'trainer/deltask/([0-9]+)' => 'trainer/deltask/$1', 
    'trainer/newtask' => 'trainer/newtask', 
    'trainer/personal/([0-9]+)' => 'trainer/personal/$1',   
    'trainer/tasks/([0-9]+)' => 'trainer/tasks/$1', 
    'trainer/del_photo/([0-9]+)' => 'trainer/del_photo/$1', 
    'trainer/view_photo/([0-9]+)' => 'trainer/view_photo/$1',   
    'trainer/photo/([0-9]+)' => 'trainer/photo/$1',
    'trainer/add/([0-9]+)' => 'trainer/add/$1', 
    'trainer/del/([0-9]+)' => 'trainer/del/$1', 
    'trainer/([0-9]+)' => 'trainer/page/$1',    
    'trainer' => 'trainer/page/0',  

    //student page
    'student/delnote/([0-9]+)' => 'student/delnote/$1', 
    'student/newnote' => 'student/newnote', 
    'student/delpriv/([0-9]+)' => 'student/delpriv/$1', 
    'student/newpriv' => 'student/newpriv', 
    'student/delblog/([0-9]+)' => 'student/delblog/$1', 
    'student/newblog' => 'student/newblog', 
    'student/awards/([0-9]+)/([0-9]+)' => 'student/awards/$1/$2',
    'student/add_award/([0-9]+)' => 'student/add_award/$1',
    'student/callback/([0-9]+)/([0-9]+)' => 'student/callback/$1/$2',   
    'student/gallery/([0-9]+)/([0-9]+)' => 'student/gallery/$1/$2', 
    'student/photo/([0-9]+)' => 'student/photo/$1', 
    'student/del_photo/([0-9]+)' => 'student/del_photo/$1', 
    'student/view_photo/([0-9]+)' => 'student/view_photo/$1', 
    'student/videos/([0-9]+)/([0-9]+)' => 'student/videos/$1/$2',   
    'student/raise/([0-9]+)' => 'student/raise/$1',	
    'student/edit' => 'student/edit',	
    'student/([0-9]+)' => 'student/page/$1',    
    'student' => 'student/page/0',  

    //login and timezone control
    'timezone' => 'site/timezone',  
    'login' => 'site/login',    
    'logout' => 'site/logout',  

    //exterior part of the site
    'help' => 'site/help',
    'special' => 'site/special',
    'about' => 'site/about',
    'bg' => 'site/bg',  
    'woman' => 'site/woman',    
    'man' => 'site/man',    
    'mail' => 'site/mail',  
    'main' => 'site/index',
    'index.php' => 'site/cover',    
    '' => 'site/cover', 
);
